#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Main.Resource", IsApplication=true)]

namespace Main
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int layout_aspectRatio = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int layout_heightPercent = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int layout_marginBottomPercent = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int layout_marginEndPercent = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int layout_marginLeftPercent = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int layout_marginPercent = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int layout_marginRightPercent = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int layout_marginStartPercent = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int layout_marginTopPercent = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int layout_widthPercent = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int daidalos_active_file = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int daidalos_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int daidalos_gray = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int daidalos_inactive_file = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Arc = 2130837505;
			
			// aapt resource value: 0x7f02000f
			public const int blue = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int blue_darkened = 2130837520;
			
			// aapt resource value: 0x7f020002
			public const int Border_5_RightBottom = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int document = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int document_gray = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int folder = 2130837509;
			
			// aapt resource value: 0x7f020011
			public const int green = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int green_darkened = 2130837522;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Lock = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int no = 2130837513;
			
			// aapt resource value: 0x7f02000e
			public const int red = 2130837518;
			
			// aapt resource value: 0x7f02000a
			public const int tick = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Unlock = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int UpArrow = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Volume = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int GraphRoot = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int Pause = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int RestButtons = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int Stop = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int TimeLeftBar = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int TimeLeftPanel = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int TimeOverBar = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int TimeOverPanel = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int WorkButtons = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int buttonAdd = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int buttonOk = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int imageViewIcon = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int linearLayoutButtons = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int linearLayoutFiles = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int rootLayout = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int scrollView1 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int textViewLabel = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int daidalos_file_chooser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int daidalos_file_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int daidalos_accept = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int daidalos_app_name = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int daidalos_cancel = 2130968581;
			
			// aapt resource value: 0x7f040010
			public const int daidalos_confirm_create_file = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int daidalos_confirm_create_folder = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int daidalos_confirm_select_file = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int daidalos_confirm_select_folder = 2130968593;
			
			// aapt resource value: 0x7f040008
			public const int daidalos_create_file = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int daidalos_create_folder = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int daidalos_enter_file_name = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int daidalos_enter_folder_name = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int daidalos_hello = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int daidalos_new_file = 2130968583;
			
			// aapt resource value: 0x7f04000e
			public const int daidalos_no = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int daidalos_ok = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int daidalos_select = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int daidalos_yes = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PercentLayout_Layout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_aspectRatio = 9;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginBottomPercent = 6;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginEndPercent = 8;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginLeftPercent = 3;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginPercent = 2;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginRightPercent = 5;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginTopPercent = 4;
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_widthPercent = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
